In [1]:
import pandas as pd

In [2]:
# The path to our CSV file
file = "201902-citibike-tripdata.csv"

# Read our Citi Bike data into pandas
df = pd.read_csv(file)
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,219,2019-02-01 00:00:06.2570,2019-02-01 00:03:46.1090,3494.0,E 115 St & Lexington Ave,40.797911,-73.942300,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,1
1,143,2019-02-01 00:00:28.0320,2019-02-01 00:02:51.7460,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,236.0,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,1
2,296,2019-02-01 00:01:13.9870,2019-02-01 00:06:10.7340,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,1
3,478,2019-02-01 00:01:14.1520,2019-02-01 00:09:12.7870,167.0,E 39 St & 3 Ave,40.748901,-73.976049,477.0,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,2
4,225,2019-02-01 00:01:49.3410,2019-02-01 00:05:34.4980,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,3443.0,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,1

In [3]:
# Get a list of all of our columns for easy reference
df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [4]:
# Extract "tripduration", "starttime", "stoptime", "start station latitude", "start station longitude", "end station latitude",
# "end station longitude", "bikeid", "usertype", "birth year", and "gender"
reduced_citibike_df = df.loc[:, ["tripduration", "starttime", "stoptime",
                                    "start station latitude", "start station longitude",
                                    "end station latitude", "end station longitude",
                                    "bikeid", "usertype", "birth year", "gender"]]
reduced_citibike_df

,tripduration,starttime,stoptime,start station latitude,start station longitude,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,219,2019-02-01 00:00:06.2570,2019-02-01 00:03:46.1090,40.797911,-73.942300,40.801487,-73.944251,33450,Subscriber,1989,1
1,143,2019-02-01 00:00:28.0320,2019-02-01 00:02:51.7460,40.727791,-73.985649,40.728419,-73.987140,25626,Subscriber,1990,1
2,296,2019-02-01 00:01:13.9870,2019-02-01 00:06:10.7340,40.676368,-73.952918,40.678045,-73.962408,35568,Subscriber,1987,1
3,478,2019-02-01 00:01:14.1520,2019-02-01 00:09:12.7870,40.748901,-73.976049,40.756405,-73.990026,25045,Subscriber,1964,2
4,225,2019-02-01 00:01:49.3410,2019-02-01 00:05:34.4980,40.763094,-73.978350,40.761330,-73.979820,34006,Subscriber,1979,1
5,457,2019-02-01 00:02:04.0010,2019-02-01 00:09:41.5640,40.709248,-73.960631,40.720368,-73.961651,33858,Subscriber,1981,2
6,175,2019-02-01 00:02:12.2960,2019-02-01 00:05:08.0930,40.722281,-73.976687,40.724537,-73.981854,24839,Subscriber,1995,1
7,248,2019-02-01 00:02:13.0450,2019-02-01 00:06:21.3960,40.802557,-73.949078,40.801307,-73.939817,31798,Subscriber,1991,1
8,541,2019-02-01 00:02:28.0750,2019-02-01 00:11:29.5490,40.730207,-73.991026,40.735238,-74.000271,32175,Subscriber,1981,0
9,406,2019-02-01 00:03:06.5420,2019-02-01 00:09:53.4310,40.734011,-74.002939,40.729515,-73.990753,27688,Subscriber,1973,2
10,659,2019-02-01 00:03:12.6290,2019-02-01 00:14:12.2660,40.728419,-73.987140,40.741022,-74.001385,31796,Subscriber,1990,1
11,1224,2019-02-01 00:03:34.3910,2019-02-01 00:23:59.3330,40.779668,-73.980930,40.784727,-73.969617,32737,Subscriber,1965,2
12,419,2019-02-01 00:03:45.0740,2019-02-01 00:10:44.1750,40.755003,-73.980144,40.763441,-73.982681,30708,Subscriber,1964,2
13,752,2019-02-01 00:03:57.2850,2019-02-01 00:16:30.1260,40.715338,-74.016584,40.722055,-73.989111,26835,Subscriber,1992,1
14,1125,2019-02-01 00:04:09.5860,2019-02-01 00:22:55.1010,40.758924,-73.962262,40.785000,-73.972834,34662,Subscriber,1985,1
15,1271,2019-02-01 00:04:55.1950,2019-02-01 00:26:06.9570,40.751726,-73.987535,40.760301,-73.998842,28893,Subscriber,1966,1
16,469,2019-02-01 00:05:12.0320,2019-02-01 00:13:01.6280,40.751551,-73.993934,40.763414,-73.996674,33856,Subscriber,1968,1
17,156,2019-02-01 00:05:13.7320,2019-02-01 00:07:49.9200,40.723117,-73.952123,40.719240,-73.952420,35009,Subscriber,1992,1
18,342,2019-02-01 00:05:22.5790,2019-02-01 00:11:05.1590,40.729515,-73.990753,40.725213,-73.977688,26739,Subscriber,1986,1
19,412,2019-02-01 00:05:30.7550,2019-02-01 00:12:22.9910,40.730477,-73.999061,40.729538,-73.984267,32911,Subscriber,1991,1
20,1007,2019-02-01 00:05:41.1090,2019-02-01 00:22:28.9800,40.760094,-73.994618,40.736245,-73.984738,35673,Customer,1994,1
21,744,2019-02-01 00:05:52.2020,2019-02-01 00:18:16.8030,40.785000,-73.972834,40.796153,-73.947821,34673,Subscriber,1994,1
22,772,2019-02-01 00:06:07.8300,2019-02-01 00:19:00.6800,40.795346,-73.961860,40.814326,-73.959025,34652,Subscriber,1984,1
23,528,2019-02-01 00:06:16.0400,2019-02-01 00:15:04.3960,40.697601,-73.993446,40.677775,-74.009461,35805,Subscriber,1993,1
24,848,2019-02-01 00:06:35.5860,2019-02-01 00:20:44.3030,40.741022,-74.001385,40.733143,-73.975739,17462,Subscriber,1997,1
25,211,2019-02-01 00:06:39.3140,2019-02-01 00:10:10.8840,40.726281,-73.989780,40.722174,-73.983688,17522,Subscriber,1980,1
26,309,2019-02-01 00:06:47.1830,2019-02-01 00:11:56.2280,40.739126,-73.979738,40.740964,-73.986022,35269,Subscriber,1977,2
27,235,2019-02-01 00:06:43.6610,2019-02-01 00:10:39.4610,40.731724,-74.006744,40.736197,-74.008592,34376,Subscriber,1963,1
28,523,2019-02-01 00:06:47.4850,2019-02-01 00:15:31.2680,40.755003,-73.980144,40.760301,-73.998842,31659,Subscriber,1987,1
29,284,2019-02-01 00:06:47.7960,2019-02-01 00:11:32.4640,40.693083,-73.971789,40.684880,-73.963040,35755,Subscriber,1991,1
...,...,...,...,...,...,...,...,...,...,...,...
943714,267,2019-02-28 23:56:03.2890,2019-03-01 00:00:30.8790,40.716021,-73.999744,40.714131,-73.997047,33748,Subscriber,1994,1
943715,486,2019-02-28 23:56:15.5460,2019-03-01 00:04:22.5070,40.708771,-73.950953,40.692371,-73.937054,35754,Subscriber,1987,2
943716,315,2019-02-28 23:56:17.7240,2019-03-01 00:01:33.6910,40.716021,-73.999744,40.714131,-73.997047,30161,Subscriber,1996,1
943717,2660,2019-02-28 23:56:35.6330,2019-03-01 00:40:56.0420,40.750182,-74.002184,40.750182,-74.002184,19976,Subscriber,1966,1
943718,143,2019-02-28 23:56:42.4210,2019-02-28 23:59:05.9350,40.727064,-73.996621,40.730386,-74.002150,30376,Subscriber,1990,1
943719,539,2019-02-28 23:56:51.7200,2019-03-01 00:05:51.6940,40.716021,-73.999744,40.720196,-73.989978,26963,Subscriber,1998,1
943720,257,2019-02-28 23:56:50.5650,2019-03-01 00:01:07.7070,40.750020,-73.969053,40.754557,-73.965930,26497,Subscriber,1962,1
943721,425,2019-02-28 23:56:58.6900,2019-03-01 00:04:04.4240,40.746201,-73.988557,40.754692,-73.997402,29950,Subscriber,1985,1
943722,276,2019-02-28 23:56:57.6020,2019-03-01 00:01:33.6360,40.679098,-73.987655,40.675162,-73.981483,33364,Subscriber,1969,0
943723,1511,2019-02-28 23:57:11.9910,2019-03-01 00:22:23.8830,40.727464,-73.979504,40.722055,-73.989111,35710,Subscriber,1975,1
943724,235,2019-02-28 23:57:30.5360,2019-03-01 00:01:26.4220,40.749370,-73.999234,40.751551,-73.993934,15818,Subscriber,1990,1
943725,372,2019-02-28 23:57:32.0280,2019-03-01 00:03:44.6870,40.727791,-73.985649,40.718939,-73.992663,20954,Subscriber,1986,1
943726,275,2019-02-28 23:57:36.3370,2019-03-01 00:02:11.9280,40.717452,-73.958509,40.712859,-73.965903,34786,Subscriber,1988,1
943727,540,2019-02-28 23:57:40.8830,2019-03-01 00:06:41.7760,40.757246,-73.978059,40.757632,-73.969306,21464,Subscriber,1983,1
943728,348,2019-02-28 23:57:41.5920,2019-03-01 00:03:29.9490,40.691966,-73.981302,40.691960,-73.965369,35579,Subscriber,1956,1
943729,220,2019-02-28 23:57:44.3790,2019-03-01 00:01:24.9520,40.725029,-73.990697,40.730473,-73.986724,32879,Subscriber,1979,1
943730,278,2019-02-28 23:58:29.1990,2019-03-01 00:03:07.7350,40.706842,-73.954435,40.703172,-73.940636,28618,Subscriber,1979,1
943731,962,2019-02-28 23:58:35.2310,2019-03-01 00:14:37.6390,40.765909,-73.976342,40.772838,-73.949892,21657,Subscriber,1991,1
943732,984,2019-02-28 23:58:46.0050,2019-03-01 00:15:10.4330,40.812551,-73.949229,40.792100,-73.973900,18618,Subscriber,1973,1
943733,819,2019-02-28 23:58:45.1040,2019-03-01 00:12:24.2090,40.748500,-73.941275,40.761227,-73.960940,15666,Subscriber,1986,1
943734,271,2019-02-28 23:58:47.4520,2019-03-01 00:03:19.0490,40.727791,-73.985649,40.720664,-73.985180,20086,Subscriber,1979,1
943735,569,2019-02-28 23:58:58.9500,2019-03-01 00:08:28.4180,40.714133,-73.952344,40.710446,-73.965251,32038,Subscriber,1980,1
943736,417,2019-02-28 23:59:28.6730,2019-03-01 00:06:26.1260,40.765849,-73.986905,40.775160,-73.989187,31628,Subscriber,1988,1
943737,468,2019-02-28 23:59:34.5080,2019-03-01 00:07:23.3040,40.756913,-73.921631,40.765625,-73.913669,29697,Subscriber,1976,1
943738,245,2019-02-28 23:59:36.0780,2019-03-01 00:03:41.0900,40.720798,-73.954847,40.714133,-73.952344,30970,Subscriber,1988,1
943739,979,2019-02-28 23:59:43.3860,2019-03-01 00:16:02.7620,40.716887,-73.963198,40.723077,-73.985836,33630,Subscriber,1992,1
943740,779,2019-02-28 23:59:48.2220,2019-03-01 00:12:47.5150,40.727434,-73.993790,40.751873,-73.977706,30765,Subscriber,1995,1
943741,699,2019-02-28 23:59:48.6480,2019-03-01 00:11:28.5880,40.747348,-73.997236,40.733143,-73.975739,19721,Subscriber,1996,1
943742,284,2019-02-28 23:59:59.2640,2019-03-01 00:04:43.6880,40.741022,-74.001385,40.750585,-73.994685,27804,Subscriber,1985,1
943743,279,2019-02-28 23:59:55.0050,2019-03-01 00:04:34.9450,40.751726,-73.987535,40.751551,-73.993934,21507,Subscriber,1969,1

In [5]:
# Remove rows without a specified gender
reduced_citibike_df = reduced_citibike_df.loc[(
    reduced_citibike_df["gender"] > 0)]
reduced_citibike_df.head()

,tripduration,starttime,stoptime,start station latitude,start station longitude,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,219,2019-02-01 00:00:06.2570,2019-02-01 00:03:46.1090,40.797911,-73.942300,40.801487,-73.944251,33450,Subscriber,1989,1
1,143,2019-02-01 00:00:28.0320,2019-02-01 00:02:51.7460,40.727791,-73.985649,40.728419,-73.987140,25626,Subscriber,1990,1
2,296,2019-02-01 00:01:13.9870,2019-02-01 00:06:10.7340,40.676368,-73.952918,40.678045,-73.962408,35568,Subscriber,1987,1
3,478,2019-02-01 00:01:14.1520,2019-02-01 00:09:12.7870,40.748901,-73.976049,40.756405,-73.990026,25045,Subscriber,1964,2
4,225,2019-02-01 00:01:49.3410,2019-02-01 00:05:34.4980,40.763094,-73.978350,40.761330,-73.979820,34006,Subscriber,1979,1

In [6]:
# Create a new column that finds the approximate age of each user
reduced_citibike_df["age"] = 2019 - reduced_citibike_df['birth year']

C:\Users\Ray\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [7]:
reduced_citibike_df.head()

,tripduration,starttime,stoptime,start station latitude,start station longitude,end station latitude,end station longitude,bikeid,usertype,birth year,gender,age
0,219,2019-02-01 00:00:06.2570,2019-02-01 00:03:46.1090,40.797911,-73.942300,40.801487,-73.944251,33450,Subscriber,1989,1,30
1,143,2019-02-01 00:00:28.0320,2019-02-01 00:02:51.7460,40.727791,-73.985649,40.728419,-73.987140,25626,Subscriber,1990,1,29
2,296,2019-02-01 00:01:13.9870,2019-02-01 00:06:10.7340,40.676368,-73.952918,40.678045,-73.962408,35568,Subscriber,1987,1,32
3,478,2019-02-01 00:01:14.1520,2019-02-01 00:09:12.7870,40.748901,-73.976049,40.756405,-73.990026,25045,Subscriber,1964,2,55
4,225,2019-02-01 00:01:49.3410,2019-02-01 00:05:34.4980,40.763094,-73.978350,40.761330,-73.979820,34006,Subscriber,1979,1,40

In [8]:
# Export the cleaned dataframe into a new CSV file
reduced_citibike_df.to_csv(r'data.csv')